### PR TITLE
Add batch write item

### PR DESCRIPTION
**Pull request by negoziator**
**---> DRAFT PULL REQUEST <---**

**Description**

Starting to work on a implentation for batch writing items.
This is to gain a lot of performance when inserting many items.

Let's see if this can be done in a clean way.

Please feel free to join in 😄 

**Notes:** 
- BatchWriteItem only supports insert of 25 items at a time - so probably something needs to check that.
- BatchWriteItem does not support updates
- The model layer don't understand "saveMany" in one go, so the query builder has to implement it.

**Documentation**
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

### CODE REVIEW

**Comment by negoziator** [comment]
Thanks @kitar ! 

I'll try it out in a real project in the coming days.

**Comment by negoziator** [comment]
Still not forgotten. I'm just testing it out on our own systems. It will take some time unfortunately - and i'm going on a week's vacation now :) 

However .. i think it would be nice to also implement BatchGetItem as well .

**Comment by kitar** [comment]
@negoziator No need to rush! Enjoy your vacation and take it at a comfortable pace :) (BTW, I won't have enough time at this time either😅)

**Comment by negoziator** [comment]
@kitar I will have to abandon this PR - as i can't make it work in a nice way with the QueryBuilder class.

**Comment by kitar** [comment]
@negoziator No problem! Thank you for letting me know and for your suggestion. It was helpful for future development :)

**Pull request closed without merging**
