### PR TITLE
Support Atomic Counters

### LINKED ISSUE #7: Support Atomic Counters
Using counter often happens because counting DynamoDB items straightforward is highly inefficient. We need to consider to support [Atomic Counters](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters).

### PR DESCRIPTION
**Pull request by mehedimi**
fixed #7

### CODE REVIEW

**Comment by kitar** [comment]
Hi @mehedimi, thank you for working on this feature! I will look into it. Please wait for a while :)

**Comment by kitar** [comment]
@mehedimi
Thanks again for your commits. `Builder` looks nice, but I've noticed few things with `Model::incrementOrDecrement`.

1. We cannot know the result value of increment/decrement before fetching the record again because this is an atomic counter.
2. `$extra` values are not syncing.

To fix 1, how about using the `UPDATED_NEW` value, which DynamoDB responds, to sync. I've made a commit to make `UpdateItem` returns response with `UPDATED_NEW` values. Please take a look at it.

https://github.com/kitar/laravel-dynamodb/commit/7a8edb50923c5323f88f9b32c624ca15641ed6f3

After fixing 1, `Model::incrementOrDecrement` could look like this. It fixes 2 as well.

```php
protected function incrementOrDecrement($column, $amount, $extra, $method)
{
    $query = $this->newQuery()->key($this->getKey());

    if (! $this->exists) {
        return $query->{$method}($column, $amount, $extra);
    }

    if ($this->fireModelEvent('updating') === false) {
        return false;
    }

    return tap($query->{$method}($column, $amount, $extra), function ($response) use ($column, $extra) {
        $extra[$column] = $response['Attributes'][$column];

        $this->forceFill($extra);

        $this->syncChanges();

        $this->fireModelEvent('updated', false);
    });
}
```

**Comment by mehedimi** [comment]
@kitar Thanks for your response. And sorry for the late response. I will push update soon! Please wait....

**Comment by mehedimi** [comment]
Hi @kitar I have updated PR. Please take a look.

**Comment by kitar** [comment]
@mehedimi looks nice! Thanks again for working on this issue. I will merge it and tag next version.

**Pull request merged**
